### PR TITLE
Add SuperSwerve

### PR DESCRIPTION
**Pull request by ACat701**
TODO:

- [x] Add back spotless
- [ ] Write the best and most gorgeous JavaDocs I can possibly write
- [ ] Reformat added files 
- [ ] Create example project?
- [ ] Replace discretize() with WPILib method (awaiting 2024 release, probably will have to be a separate issue)

### CODE REVIEW

**Review by TaylerUva — CHANGES_REQUESTED** [review]
This will not compile, you need to make your class names match your file names

image

**Comment by TaylerUva** [comment]
REV Vendor rep needs to be updated and old build.gradle worked fine just need to update versions:
```java
    id "edu.wpi.first.GradleRIO" version "2023.4.2"
    id 'com.diffplug.spotless' version '6.12.0'
````

**Comment by ACat701** [comment]
I'm not going to bother with auto-formatting until we are ready to merge this in because the auto-formatter appears to hate me 
WhatsApp Image 2023-12-19 at 00 34 30_b34a3303

**Comment by ACat701** [comment]
Opening this for review because I think I'm done with the JavaDocs. If you'd like any changes to them feel free to comment.
Please autoformat this for me before you merge it in

**Review by TaylerUva — APPROVED** [review]

**Pull request merged**
