### PR TITLE
Enable Local Publishing

### PR DESCRIPTION
**Pull request by TaylerUva**
Enables the ability to publish SuperCORE locally to test new changes to SuperCORE on Robot Projects locally

### CODE REVIEW

**Review by ACat701 — COMMENTED** [review]
This looks great! However, as I was following the instructions and running
cleanPublishSuperCORELocalDev, I did get an error: 
image

I tried making changes to the SN_SuperSwerve constructor and then following the instructions, ignoring this error, but they didn't take effect. If I'm doing something wrong you can let me know and possibly clarify that in the README

**Comment by TaylerUva** [comment]
I forgot that the createWebFolders script is using bash, which only works out of the box for macOS and Linux. I will have to figure out a fix for Windows

**Comment by TaylerUva** [comment]
Try it now @ACat701

**Review by ACat701 — APPROVED** [review]
It works now :D
seal-approval

**Pull request merged**
